### ISSUE TITLE
Segmentation fault or stuck when set num_workers>0

### ISSUE THREAD

**Issue by InkosiZhong** [stanford-futuredata/tasti#3]
Thanks for your excellent work. 
However, I find a segmentation fault will occur when I set `num_workers>=2` (which is 56 in your default implementation) to run `night_street_offline.py`,
```bash
Embedding DNN:   0%|                                  | 0/60844 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault encountered in worker.
Embedding DNN:   0%|                                  | 0/60844 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2113115) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tasti/examples/night_street_offline.py", line 273, in <module>
    index.init()
  File "/home/inkosizhong/Lab/VideoQuery/tasti/tasti/index.py", line 245, in init
    self.do_mining()
  File "/home/inkosizhong/Lab/VideoQuery/tasti/tasti/index.py", line 101, in do_mining
    for batch in tqdm(dataloader, desc='Embedding DNN'):
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1315, in _get_data
    success, data = self._try_get_data()
  File "/home/inkosizhong/anaconda3/envs/tasti3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 2113115) exited unexpectedly
```
If I change the `num_worker` into 1, the progress stuck and seems deadlocked.
```bash
Embedding DNN:   0%|                                             | 0/60844 [00:00<?, ?it/s]
```
The mining process only works when I set `num_worker=0` which means completely disabling prefetching, causing the mining speed to be very slow.
My CPU is i9-9900kf which contains 8 cores (16 threads).
I find that you use `swag.VideoCapture` which is an encapsulation of `cv2.VideoCapture` in the `VideoDataset`. 
**I'm curious, since video decoding has inter-frame dependencies, how does this parallel prefetching (`num_worker>0`) work? And why doesn't it work on my machine?**

**Comment by InkosiZhong** [comment]
Supplement: The same problem happens in `do_training` and `do_infer`.

**Comment by ddkang** [comment]
This is an issue with the Pytorch dataloader and OpenCV interactions. To reproduce results, please use single threaded.

If you have a fix, we'd love to see a PR though.

**Comment by InkosiZhong** [comment]
So, are you also using a single thread during your experiments? Then why is it 56 in the code?

**Comment by ddkang** [comment]
It works in an older version of Pytorch.

**Comment by InkosiZhong** [comment]
I want to know which version is it? Thank you very much.

**Comment by ddkang** [comment]
Unfortunately I don't remember the OpenCV / Pytorch combination. However, you can write a C++ version to extract the videos efficiently. Our other repository, smol, does this

**Comment by InkosiZhong** [comment]
Ok, thanks so much
